Repository ItsEcholot/ContainerNursery, pull requests merged in 2021-09, with the labels that each got.

#5 Feature/proper logging
  .dockerignore
  README.md
  nodemon.json
  package-lock.json
  package.json
  src/ConfigManager.ts
  src/Logger.ts
  src/ProxyHost.ts
  src/index.ts
Labels: enhancement

#9 Feature/container events
  package-lock.json
  package.json
  src/ConfigManager.ts
  src/DockerManager.ts
  src/ProxyHost.ts
Labels: enhancement, testing underway

#14 Additional Solution: Configurable Proxy Listening Port
  .gitignore
  README.md
  config/config.yml.example
  src/ConfigManager.ts
  src/index.ts
Labels: testing underway

#19 Feature/prevent stop cpu usage
  .eslintrc
  README.md
  config/config.yml.example
  package.json
  src/ConfigManager.ts
  src/ProxyHost.ts
Labels: testing underway

#23 Feature/multiple containers
  README.md
  config/config.yml.example
  package.json
  src/ConfigManager.ts
  src/DockerManager.ts
  src/ProxyHost.ts
Labels: testing underway
